openapi: 3.0.3
info:
  title: OpenAPISpec - Game
  description: |-
    This is the OpenAPISepc for the game that will be created during the module "Moderne Software-Architekturen".
  version: 0.0.1
tags:
  - name: move
    description: a move that a player can do
  - name: game
    description: a game that can be or was played
paths:
  /game:
    post:
      tags:
        - game
      summary: Adds a new game
      description: Adds a new game and returns the game ID.
      operationId: addGame
      responses:
        "200":
          description: Successful operation, game created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the created game
                example:
                  id: 1
        "400":
          description: Invalid input
  /game/{id}/move:
    post:
      tags:
        - move
      summary: Move the player in the maze
      description: Moves the player in the specified direction within the game
      operationId: addMove
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the game
        - name: direction
          in: query
          required: true
          schema:
            type: string
            enum: ["up", "down", "left", "right"]
          description: Direction in which to move the player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                direction:
                  type: string
                  enum: ["up", "down", "left", "right"]
                  description: The direction in which the player wants to move
              example:
                direction: "left"
      responses:
        "200":
          description: Move request successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ["blocked", "success", "failed"]
                    description: The status of the move (blocked, if there's a wall; success, if the move succeeded; failed, if moving out of bounds)
                  position:
                    type: string
                    description: The new position of the player
                    example: "A3"
        "400":
          description: Invalid input
        "404":
          description: Game not found
components:
  schemas:
    game:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        finished:
          type: boolean
    move:
      type: object
      properties:
        direction:
          type: string
          example: left, right, up, down
        status:
          type: string
          example: blocked, success, failed
        position:
          type: string
          example: A3
